apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "todo-app-chart.name" . }}
  labels:
    app: {{ include "todo-app-chart.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "todo-app-chart.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "todo-app-chart.name" . }}
    spec:
      containers:
        - name: my-app-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - name: app-port
              containerPort: {{ .Values.containerPort }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
