apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-app-chart.name" . }}
  labels:
    app: {{ include "todo-app-chart.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app: {{ include "todo-app-chart.name" . }}
